
--
-- Table structure for table user
--

CREATE TABLE user (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  user_name varchar(255) NOT NULL,
  password varchar(255) NOT NULL,
  password_question varchar(255) DEFAULT NULL,
  password_answer varchar(255) DEFAULT NULL,
  create_date datetime NOT NULL,
  invalid_attempts INT NULL,
  lock_date datetime NULL,
  active BIT NOT NULL
);

--
--  data for table user
--

INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('mscott','Holly1234',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('jhalpert','4PamAgain',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('pbeesly','JimNotRoy',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('dschrute','AngelaBeets',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('amartin','CatLadyA',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('abernard','1BigTuna',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('dwallace','DownWithSabre',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('tflenderson','CostaRica',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);
INSERT INTO user (user_name, password, password_question, password_answer, create_date, invalid_attempts, lock_date, active) VALUES ('hflax','JazzyFlax',NULL,NULL,'2014-03-11 09:57:38', 0, NULL, 1);

--
-- Table structure for table customer
--

CREATE TABLE customer (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  company varchar(50) DEFAULT NULL,
  last_name varchar(50) NOT NULL,
  first_name varchar(50) NOT NULL,
  email_address varchar(50) DEFAULT NULL,
  job_title varchar(50) DEFAULT NULL,
  business_phone varchar(25) DEFAULT NULL,
  home_phone varchar(25) DEFAULT NULL,
  mobile_phone varchar(25) DEFAULT NULL,
  fax_number varchar(25) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  postal_code varchar(15) DEFAULT NULL,
  country varchar(50) DEFAULT NULL,
  web_page LONGVARCHAR,
  notes LONGVARCHAR,
  attachments LONGVARCHAR,
);

--
-- Data for table customer
--
--REAL DATA
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Dunder Mifflin','Flenderson','Toby', 'Toby.Flenderson@dm.paper','Mr.',NULL,NULL,'570-836-8200',NULL,'4568 90th Avenue','Scranton','PA','18519','US',NULL,NULL,NULL);

--FAKE DATA FOR DUMP DEMO
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Awthentikz','Pringle','Susan','SusanSPringle@superrito.com','Photographic retoucher',NULL,NULL,'541-564-5277',NULL,'2488 Haymond Rocks Road','Hermiston','OR','97838','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Monsource','Castro','Jennifer','JenniferDCastro@cuvox.de','Fish and game warden',NULL,NULL,'909-935-7853',NULL,'2933 Clarence Court','Los Angeles','CA','90017','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Chandler''s','Taylor','Jennifer','JenniferATaylor@einrot.com','Administrative services director',NULL,NULL,'724-712-1101',NULL,'789 Michigan Avenue','Pittsburgh','PA','15201','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('De-Jaiz Mens Clothing','Cooper','Tracy','TracySCooper@gustr.com','Administrative project coordinator',NULL,NULL,'847-557-6230',NULL,'602 Thomas Street','Chicago','IL','60601','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Cut Above','Fox','Katherine','KatherineMFox@einrot.com','Music conductor',NULL,NULL,'408-844-7423',NULL,'3619 Black Oak Hollow Road','Santa Clara','CA','95054','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('J. Riggings','Parisien','James','JamesRParisien@cuvox.de','Lift truck operator',NULL,NULL,'636-234-1952',NULL,'3300 Irving Place','Saint Louis','MO','63101','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Disc Jockey','White','AlINSERT INTO customer VALUES fred','AlfredHWhite@jourrapide.com','Social work planner',NULL,NULL,'301-258-0585',NULL,'3068 Roane Avenue','Gaithersburg','MD','20877','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Showbiz Pizza Place','Walker','Steve','SteveCWalker@rhyta.com','Obstetric sonographer',NULL,NULL,'817-593-1208',NULL,'4390 Sardis Sta','Fort Worth','TX','76102','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Montana''s Cookhouse','Parish','Meghan','MeghanAParish@superrito.com','Heating equipment technician',NULL,NULL,'802-888-6298',NULL,'1085 Marion Street','Morrisville','VT','05661','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Magna Consulting','Doherty','Jimmy','JimmyADoherty@jourrapide.com','Cooking instructor',NULL,NULL,'618-937-8477',NULL,'1424 Davis Court','West Frankfort','IL','62896','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Pantry Food Stores','Eno','Kelly','KellyDEno@teleworm.us','Model maker',NULL,NULL,'860-251-3936',NULL,'3006 Hart Street','Hartford','CT','06103','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Hughes & Hatcher','Wallace','Anna','AnnaCWallace@teleworm.us','HVACR technician',NULL,NULL,'248-901-1876',NULL,'2675 Summit Park Avenue','Birmingham','MI','48011','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Big Daddy''s Restaurants','Ewell','Christopher','ChristopherTEwell@jourrapide.com','Electrical drafter',NULL,NULL,'434-979-4751',NULL,'1726 North Street','Charlottesville','VA','22903','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Piece Goods Fabric','Yazzie','Billy','BillyMYazzie@gustr.com','Poet',NULL,NULL,'785-524-8209',NULL,'288 Sigley Road','Lincoln','KS','67455','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Jackpot Consultant','Lawson','Maria','MariaLLawson@teleworm.us','Assistant principal',NULL,NULL,'775-719-9051',NULL,'2680 Martha Ellen Drive','Reno','NV','89501','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Helios Air','Jobe','Katherine','KatherineJJobe@einrot.com','Transportation, storage, and distribution manager',NULL,NULL,'734-533-3436',NULL,'1579 Daylene Drive','Southfield','MI','48075','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Olympic Sports','Vincent','Marcus','MarcusJVincent@superrito.com','Payroll coordinator',NULL,NULL,'517-418-7635',NULL,'4087 Elk Avenue','Lansing','MI','48933','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Megatronic Plus','Moore','Anita','AnitaTMoore@gustr.com','Private banker',NULL,NULL,'478-640-4784',NULL,'3238 Graystone Lakes','Macon','GA','31213','US',NULL,NULL,NULL)
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Ole''s','Joy','Doris','DorisPJoy@armyspy.com','Insurance sales agent',NULL,NULL,'281-948-9328',NULL,'234 Gambler Lane','Houston','TX','77032','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Gart Sports','Bryan','Jo','JoJBryan@gustr.com','Rigger',NULL,NULL,'850-379-5305',NULL,'512 Star Trek Drive','Blountstown','FL','32424','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Exact Solutions','Dickerson','Roxanne','RoxanneJDickerson@teleworm.us','Polisher',NULL,NULL,'870-476-9230',NULL,'2445 Rosebud Avenue','Blytheville','AR','72315','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Endicott Shoes','Conover','Maria','MariaCConover@teleworm.us','Corporate office services manager',NULL,NULL,'904-677-7158',NULL,'2874 Boundary Street','Jacksonville','FL','32202','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('System Star','Heath','Mable','MableDHeath@rhyta.com','Assistant editor',NULL,NULL,'919-575-7845',NULL,'3551 Nancy Street','Creedmoor','NC','27522','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Vitamax Health Food Center','Barnes','Lucy','LucyJBarnes@einrot.com','Videographer',NULL,NULL,'417-995-8112',NULL,'4724 Davis Place','Dadeville','MO','65635','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('One-Up Realtors','Wilkerson','Elmer','ElmerRWilkerson@superrito.com','Financial clerk',NULL,NULL,'270-429-3414',NULL,'2471 Glen Street','Hopkinsville','KY','42240','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Thrift Auto Parts','Golden','Scott','ScottAGolden@einrot.com','Certified athletic trainer',NULL,NULL,'713-428-4513',NULL,'4993 Monroe Street','Houston','TX','77002','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Jackpot Consultant','Delavega','Amber','AmberDDelavega@dayrep.com','Delivery service driver',NULL,NULL,'334-598-7691',NULL,'2069 Turkey Pen Lane','Daleville','AL','36322','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Star Assistance','Mason','David','DavidJMason@armyspy.com','Junior high school teacher',NULL,NULL,'479-878-0307',NULL,'3197 Cambridge Court','Rogers','AR','72756','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Bountiful Harvest Health Food Store','Sanchez','Stacey','StaceyASanchez@cuvox.de','Petroleum pump system operator',NULL,NULL,'303-988-3114',NULL,'2823 Tavern Place','Lakewood','CO','80227','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Environ Architectural Design','Green','Richard','RichardJGreen@armyspy.com','Landlord',NULL,NULL,'801-633-3217',NULL,'4387 Tori Lane','Salt Lake City','UT','84116','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Manning''s Cafeterias','Gipson','Andrew','AndrewCGipson@gustr.com','CNC programmer',NULL,NULL,'270-213-7908',NULL,'2646 Broaddus Avenue','Madisonville','KY','42431','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('GEX','Jenkins','Bobby','BobbyEJenkins@superrito.com','Driver-sales worker',NULL,NULL,'740-222-1723',NULL,'2394 Bombardier Way','Westerville','OH','43081','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Mr. Clark''s Appliances','Holden','Paul','PaulHHolden@fleckens.hu','School bus driver',NULL,NULL,'717-770-3446',NULL,'3104 Aaron Smith Drive','New Cumberland','PA','17070','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Strength Gurus','Damron','Grace','GraceJDamron@rhyta.com','Gaming cage worker',NULL,NULL,'870-281-0161',NULL,'935 Fittro Street','Texarkana','AR','75501','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Knockout Kickboxing','Coleman','Beverly','BeverlyPColeman@gustr.com','Painter',NULL,NULL,'801-922-7405',NULL,'1560 Kemper Lane','Salt Lake City','UT','84104','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Body Fate','Bunnell','Brian','BrianMBunnell@fleckens.hu','Power plant dispatcher',NULL,NULL,'630-333-5727',NULL,'4483 Fraggle Drive','Chicago','IL','60606','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Super Duper','Groves','Leonard','LeonardLGroves@gustr.com','Clock repairer',NULL,NULL,'763-549-2511',NULL,'3810 Hillcrest Circle','Brooklyn Center','MN','55430','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Gas Depot','Aubin','Thomas','ThomasEAubin@fleckens.hu','Home health nurse',NULL,NULL,'305-208-0449',NULL,'3090 Agriculture Lane','Miami','FL','33145','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('De-Jaiz Mens Clothing','Fuller','James','JamesCFuller@gustr.com','Food preparation worker',NULL,NULL,'605-943-7190',NULL,'658 Leroy Lane','Ree Heights','SD','57371','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Sounds of Soul Records & Tapes','Hersh','Robert','RobertRHersh@gustr.com','Camp counselor',NULL,NULL,'956-581-4507',NULL,'2605 Adamsville Road','Mission','TX','78572','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('K''s Merchandise','Epperson','Lloyd','LloydREpperson@rhyta.com','Sous chef',NULL,NULL,'612-924-3656',NULL,'761 Rocket Drive','Minneapolis','MN','55410','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Modern Realty','Stock','Christopher','ChristopherJStock@dayrep.com','Economist',NULL,NULL,'209-559-5249',NULL,'1365 Dennison Street','Stockton','CA','95219','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('First Choice Yard Help','Hernandez','Connie','ConnieWHernandez@dayrep.com','Operating room technician',NULL,NULL,'715-687-8317',NULL,'4737 Mercer Street','Stratford','WI','54484','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Planet Pizza','Baxter','Maria','MariaJBaxter@armyspy.com','Escort interpreter',NULL,NULL,'318-649-5226',NULL,'4429 Emerson Road','Columbia','LA','71418','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Fresh Start','Gunnels','Cynthia','CynthiaGGunnels@armyspy.com','Corporate administrative assistant',NULL,NULL,'201-305-4075',NULL,'1996 West Side Avenue','New Brunswick','NJ','08901','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Solution Answers','Watt','John','JohnRWatt@rhyta.com','Locker room attendant',NULL,NULL,'910-675-0483',NULL,'2206 Armory Road','Castle Hayne','NC','28429','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('EnviroSource Design','Carter','Zona','ZonaJCarter@fleckens.hu','Self enrichment teacher',NULL,NULL,'240-776-7231',NULL,'4361 Bobcat Drive','Washington','MD','20200','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Tweeter','Garcia','Mark','MarkAGarcia@jourrapide.com','Transmission rebuilder',NULL,NULL,'313-461-4078',NULL,'3578 Woodbridge Lane','Detroit','MI','48226','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Pro Yard Services','Kinsey','Travis','TravisPKinsey@cuvox.de','Ship officer',NULL,NULL,'828-508-6529',NULL,'4113 Diamond Street','Sylva','NC','28779','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Sounds of Soul Records & Tapes','Jordan','Douglas','DouglasPJordan@gustr.com','Materials engineer',NULL,NULL,'401-776-0332',NULL,'4513 Bond Street','Providence','RI','02905','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Thorofare','Templeton','Angelique','AngeliqueATempleton@jourrapide.com','Facilitator',NULL,NULL,'419-388-2678',NULL,'3713 Olive Street','Lansing','OH','48911','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Edge Garden Services','Kempf','Tammy','TammyJKempf@jourrapide.com','Chief information officer',NULL,NULL,'843-276-2248',NULL,'409 Poe Road','Charleston','SC','29403','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Forest City','Collins','Spencer','SpencerLCollins@cuvox.de','Interior designer',NULL,NULL,'419-868-2562',NULL,'764 Upland Avenue','Holland','OH','43528','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Royal Gas','Setliff','Linda','LindaFSetliff@cuvox.de','Office machine operator',NULL,NULL,'650-207-3861',NULL,'2083 Ella Street','San Francisco','CA','94107','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Laura Ashley','Jones','James','JamesHJones@fleckens.hu','Tool grinder',NULL,NULL,'815-689-9067',NULL,'1444 Spinnaker Lane','Cullom','IL','60929','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Fresh Start','Smith','George','GeorgeJSmith@jourrapide.com','Combined food preparation and serving worker',NULL,NULL,'251-706-8767',NULL,'2654 Joyce Street','Mobile','AL','36606','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Mars Music','Franklin','William','WilliamAFranklin@teleworm.us','Employee benefits manager',NULL,NULL,'561-607-0453',NULL,'2851 Powder House Road','West Palm Beach','FL','33411','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Wealthy Ideas','Peltier','Donald','DonaldDPeltier@armyspy.com','Auditing clerk',NULL,NULL,'718-998-8762',NULL,'2320 Lady Bug Drive','Brooklyn','NY','11223','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Terra','Cashman','Angelo','AngeloTCashman@fleckens.hu','Photographer',NULL,NULL,'508-677-5369',NULL,'2778 Randolph Street','Fall River','MA','02720','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Gamma Grays','Young','Adam','AdamBYoung@superrito.com','Termite control technician',NULL,NULL,'254-742-2066',NULL,'1124 Clair Street','Temple','TX','76501','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Webcom Business Services','Velasquez','Robert','RobertJVelasquez@armyspy.com','Justice of the peace',NULL,NULL,'732-212-7983',NULL,'3022 Pooz Street','Red Bank','NJ','07701','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Klopfenstein''s','Madison','Melissa','MelissaMMadison@rhyta.com','Military officer',NULL,NULL,'301-522-5313',NULL,'2552 Doe Meadow Drive','Rockville','MD','20852','US',NULL,NULL,NULL);
INSERT INTO customer (company, last_name, first_name, email_address, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments) VALUES ('Tee Town','Newkirk','Victor','VictorBNewkirk@armyspy.com','Oceanographer',NULL,NULL,'618-988-1160',NULL,'815 Holden Street','Herrin','IL','62948','US',NULL,NULL,NULL);

--
-- Table structure for table employee
--

CREATE TABLE employee (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  company varchar(50) DEFAULT NULL,
  email_address varchar(50) DEFAULT NULL,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  job_title varchar(50) DEFAULT NULL,
  business_phone varchar(25) DEFAULT NULL,
  home_phone varchar(25) DEFAULT NULL,
  mobile_phone varchar(25) DEFAULT NULL,
  fax_number varchar(25) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  city varchar(50) DEFAULT NULL,
  state varchar(50) DEFAULT NULL,
  postal_code varchar(15) DEFAULT NULL,
  country varchar(50) DEFAULT NULL,
  web_page LONGVARCHAR,
  notes LONGVARCHAR,
  attachments LONGVARCHAR,
  user_id INT DEFAULT NULL,
  dob datetime DEFAULT NULL,
  ssn varchar(255) DEFAULT NULL,
  gender varchar(6) DEFAULT NULL,
  vehicle varchar(255) DEFAULT NULL,
  height varchar(255) DEFAULT NULL,
  weight varchar(255) DEFAULT NULL,
  w4_marital_status varchar(255) DEFAULT NULL,
  w4_exempt varchar(255) DEFAULT NULL,
  w4_additional_withholding varchar(255) DEFAULT NULL,
  routing_number varchar(255) DEFAULT NULL,
  bank_account_number varchar(255) DEFAULT NULL,
  manager_id INT DEFAULT NULL,
  CONSTRAINT employee_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT employee_ibfk_2 FOREIGN KEY (manager_id) REFERENCES employee (id)
);

--
-- Dumping data for table employee
--

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Michael.Scott@dm.paper','Michael','Scott','Regional Manager','570-541-7787',NULL,NULL,NULL,'490 Farland Avenue','Scranton','PA','18505','US',NULL,NULL,NULL,1,'1976-08-24 00:00:00','652-32-4376','male','2004 Chrysler Sebring Limited','5'' 8','165.7','Married','0','0.00','301281926','4539419032791455', NULL);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Jim.Halpert@dm.paper','Jim','Halpert','Assistant Regional Manager','570-248-4033',NULL,NULL,NULL,'4688 Felosa Drive','Scranton','PA','18503','US',NULL,NULL,NULL,2,'1978-03-30 00:00:00','353-12-8894','male','2005 Saab 9-2x','6'' 3','191.0','Single','0','0.00','161221337','5201764622497714', 1);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Pam.Beesly@dm.paper','Pam','Beesly','Office Manager','570-418-8442',NULL,NULL,NULL,'1886 Deer Haven Drive','Scranton','PA','18504','US',NULL,NULL,NULL,3,'1981-03-02 00:00:00','624-44-3188','female','2007 Toyota Yaris','5'' 9','153.1','Married','0','0.00','465213640','4539152005952354', 1);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Dwight.Schrute@dm.paper','Dwight','Schrute','Sales Manager','570-683-3009',NULL,NULL,NULL,'501 John Daniel Drive','Scranton','PA','18507','US',NULL,NULL,NULL,4,'1963-07-03 00:00:00','555-90-8316','male','1987 Pontiac Trans Am','5'' 11','229.0','Single','0','0.00','101118522','5200195936476469', 1);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Angela.Martin@dm.paper','Angela','Martin','Account Controller','570-774-3470',NULL,NULL,NULL,'1177 Hill Street','Scranton','PA','18509','US',NULL,NULL,NULL,5,'1971-11-14 00:00:00','667-12-6436','female','2003 Ford Focus','4'' 11','180.8','Married','0','0.00','273928466','4485348923942634', 1);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Andy.Bernard@dm.paper','Andy','Bernard','Customer Service Rep','570-834-4216',NULL,NULL,NULL,'3979 Heavner Avenue','Scranton','PA','18512','US',NULL,NULL,NULL,6,'1971-05-01 00:00:00','375-82-2514','male','2001 Nissan Xterra SE','5'' 9','181.5','Single','0','0.00','301281931','4532617984438788', 1);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','David.Wallace@dm.paper','David','Wallace','Chief Financial Officer','570-875-9876',NULL,NULL,NULL,'435 Golden Creek Dr','Scranton','PA','18510','US',NULL,NULL,NULL,6,'1969-05-01 00:00:00','553-23-2144','male','2010 BMW 7 Series','5'' 11','202.5','Single','0','0.00','052528640','69296776555443', NULL);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Toby.Flenderson@dm.paper','Toby','Flenderson','HR Representative','570-836-8200',NULL,NULL,NULL,'4568 90th Avenue','Scranton','PA','18519','US',NULL,NULL,NULL,6,'1971-05-01 00:00:00','321-80-3598','male','2008 Saab 9-2x wagon','5'' 9','198.5','Single','0','0.00','052485125','5746953201258456', 7);

INSERT INTO employee (company, email_address, first_name, last_name, job_title, business_phone, home_phone, mobile_phone, fax_number, address, city, state, postal_code, country, web_page, notes, attachments, user_id, dob, ssn, gender, vehicle, height, weight, w4_marital_status, w4_exempt, w4_additional_withholding, routing_number, bank_account_number, manager_id)
VALUES ('Dunder Mifflin','Hollis.Flax@dm.paper','Hollis','Flax','HR Representative','570-334-0303',NULL,NULL,NULL,'987 Heavenly Rd','Scranton','PA','18518','US',NULL,NULL,NULL,6,'1971-05-01 00:00:00','322-33-0304','female','2007 Toyota Camry Solara','5'' 9','123.5','Single','0','0.00','052543440','3446953212255665', 7);

--
-- Table structure for table knowledge_base
--

CREATE TABLE knowledge_base (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  title varchar(50) DEFAULT NULL,
  url LONGVARCHAR,
  notes LONGVARCHAR,
  tags LONGVARCHAR
);

--
-- Dumping data for table knowledge_base
--

INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Dwight''s Super Desk','https://timedotcom.files.wordpress.com/2015/03/screen-shot-2015-03-23-at-4-07-43-pm.png?w=720','Suspected Halpert prank.','Pranks');
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Dwight''s Clone','https://youtu.be/WaaANll8h18','Harassment of co-worker','Escalte to management');
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Parking Lot Accident','https://youtu.be/lqivZzA2dvY','Call the HR department: https://youtu.be/GFn5vD0HDKk',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Substance Abuse at Work','https://youtu.be/NHh0rf0ojEc','Police departemnt investigation',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('JK Wedding Entrance','https://vimeo.com/6986692','Get your dance groove on.',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('TV Repair','https://youtu.be/qqeN_h3lk5E','It is cheaper to purchase a new $200 TV.',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Medical Emergency','https://vimeo.com/136822167','Employees should call 911 and perform CPR if necessary.',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Financial Assistance','https://youtu.be/HuGIgf-ICHM','File for chapter 11 bankruptcy if necessary.',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Carpet Cleaning Service','https://youtu.be/HMGK61Jqq3c','Use approved carpet cleaning vendor.',NULL);
INSERT INTO knowledge_base (title, url, notes, tags) VALUES ('Clock Repiar','https://youtu.be/GBkJjHVeqow','Locate and replace clock batteries.',NULL);

--
-- Table structure for table ticket
--

CREATE TABLE ticket (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  title varchar(150) NOT NULL,
  assigned_to_id INT DEFAULT NULL,
  customer_id INT DEFAULT NULL,
  opened_by_id INT DEFAULT NULL,
  opened_date datetime NOT NULL,
  status varchar(50) DEFAULT NULL,
  category varchar(50) DEFAULT NULL,
  priority varchar(50) DEFAULT NULL,
  description LONGVARCHAR,
  due_date datetime DEFAULT NULL,
  comments LONGVARCHAR,
  resolved_date datetime DEFAULT NULL,
  kb_id INT DEFAULT NULL,
  attachments LONGVARCHAR,
  CONSTRAINT ticket_ibfk_4 FOREIGN KEY (kb_id) REFERENCES knowledge_base (id),
  CONSTRAINT ticket_ibfk_5 FOREIGN KEY (assigned_to_id) REFERENCES employee (id),
  CONSTRAINT ticket_ibfk_2 FOREIGN KEY (customer_id) REFERENCES customer (id),
  CONSTRAINT ticket_ibfk_3 FOREIGN KEY (opened_by_id) REFERENCES employee (id)
);

--
-- Dumping data for table ticket
-- (Michael (1), Jim (2), Pam (3), Dwight (4), Angela (5), Andy (6), David (7), Toby (8), Holly (9)

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('The Super Desk',2,1,4,'2010-03-11 19:08:02','Assigned','Office Prank','Low','As retaliation to the Super Desk that Dwight constructed, Jim stacked desks together to create the Quad Desk - making Dwight unable to work.',NULL,'Dwight then created a small space between the desks, thus allowing Dwight to continue his work.',NULL,1,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Dwight Clone',1,1,4,'2007-04-26 19:11:35','Assigned','Harassment','Medium','Jim won''t stop impersonating Dwight. He has dressed as him with a matching tie, glasses and briefcase.  Won''t stop claiming that the Black Bear is best and disrespecting beets.','2016-12-31 19:11:35','Dwight ran to Michael who was able to intervene and calm tensions. Case considered closed until the next round of pranks between Dwight and Jim.', NULL, 2, NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Parking Lot Accident',8,1,8,'2007-09-27 19:11:39','Submitted','Workers Compensation','High','Michael hit Meredith with his car.',NULL,'Immediate attention to Meredith at hospital, in which she will be fine.',NULL,3,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Drug Abuse Case',9,1,1,'2008-11-20 19:11:39','Assigned','Substance Abuse','High','Michael has called in and is upset that Toby has returned to work at Dunder Mifflin. He decided to place "drugs" in his desk to try and get him fired.','2017-02-10 19:11:39','Determined that the drugs are a bag of caprese salad, complete with mozzarella cheese. Toby explained to Michael that he wasted the police officers time.',NULL,4,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Wedding Song List',6,1,3,'2009-10-08 19:11:39','Submitted','Office Romance','High','Pam specifically asked the wedding party to not dance to the YouTube viral sensation JK Wedding Entrance.','2014-02-10 19:11:39','Jim explains that he had prepared the ferry marriage in advance after seeing the video, predicting the guests might imitate it.',NULL,5,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Dinner Party Blunder',7,1,1,'2008-04-10 19:11:39','Submitted','Destruction of Property','Low','After a failed dinner party with employees of Dunder Mifflin, Jan throws a Dundie and breaks Michael''s $200 plasma television.','2017-04-28 19:11:39','Jan continued to sell her homemade candles to pay Michael back for the $200 flat screen plasma television.',NULL,6,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Prank Fire Drill',1,1,4,'2009-02-01 19:11:39','Submitted','Emergency Health Problem','Low','Dwight wanted to simulate a fire in the office to see how everyone would respond and ultimately Stanley collapsed from a heart attack.','2017-02-02 19:11:39','Michael has come up with stress relief options for the office with a comedic roast of himself to ease tensions.',NULL,7,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Michael''s Bankruptcy',5,1,1,'2007-10-18 19:11:39','Submitted','Financial Assistance','Low','Michael is in financial trouble as Jan moved in with him and wants to renovate his condo.  He tried to declare bankruptcy by shouting the word "bankruptcy".','2017-02-02 19:11:39','He will need to file appropriate documentation and forms if he wishes to formally file for bankruptcy.',NULL,8,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Chili Carpet Stain',1,1,3,'2009-04-30 19:11:39','Assigned','Office Potluck','Low','Kevin spilled an entire pot of his famous chili on the Dunder Mifflin office floor.','2017-02-02 19:11:39','Attempts to clean this up failed and carpet must be steam cleaned.',NULL,9,NULL);

INSERT INTO ticket (title, assigned_to_id, customer_id, opened_by_id, opened_date, status, category, priority, description, due_date, comments, resolved_date, kb_id, attachments)
VALUES ('Clock Maintenance',8,1,6,'2010-10-28 19:11:39','Closed','Office Maintenance','Low','Although Stanley did not notice a number of pranks that were pulled on him throughout the day, he did take notice that the clock is running 5 minutes slow.','2017-02-02 19:11:39','Maintenance team placed new batteries in the clock.',NULL,10,NULL);

--
-- Table structure for table role
--

CREATE TABLE role (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  name varchar(255) NOT NULL,
  description varchar(255) DEFAULT NULL
);

--
-- Data for table role
--

INSERT INTO role (name, description) VALUES ('Manager','Grants rights to manage the employee accounts');

--
-- Table structure for table phone_call
--

CREATE TABLE phone_call (
  id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
  call_time datetime DEFAULT NULL,
  notes LONGVARCHAR,
  ticket_id INT DEFAULT NULL,
  CONSTRAINT phone_call_ibfk_1 FOREIGN KEY (ticket_id) REFERENCES ticket (id)
);

--
-- Dumping data for table phone_call
--

INSERT INTO phone_call (call_time, notes, ticket_id) VALUES ('2010-03-11 19:08:02',NULL,1);
INSERT INTO phone_call (call_time, notes, ticket_id) VALUES ('2007-04-26 19:11:35',NULL,2);
INSERT INTO phone_call (call_time, notes, ticket_id) VALUES ('2007-09-27 19:11:35',NULL,3);
INSERT INTO phone_call (call_time, notes, ticket_id) VALUES ('2008-11-02 19:11:35',NULL,4);


--
-- Table structure for table user_role
--

CREATE TABLE user_role (
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  PRIMARY KEY (user_id,role_id),
  CONSTRAINT user_role_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (id),
  CONSTRAINT user_role_ibfk_2 FOREIGN KEY (role_id) REFERENCES role (id)
);

INSERT INTO user_role VALUES (1,1);
INSERT INTO user_role VALUES (7,1);
