# export COSIGN_API_PUB_KEY=$(cosign public-key --key "hashivault://dm-api" 2>/dev/null)
# gomplate -f ./cosign-cluster-image-policy.yaml.tmpl
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: trust-signed-dm-images
spec:
  mode: warn
  images:
    - glob: "*.dkr.ecr.*.amazonaws.com/dm**"
    - glob: "*.dkr.ecr.*.amazonaws.com/public**"
    - glob: "dminfra*.azurecr.io/dm/**"
    - glob: "dminfra*.azurecr.io/public/**"
  authorities:
    - key:
        data: |
          -----BEGIN PUBLIC KEY-----
          MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE36mam0vVbsppPBux5xyhSs1FPuQN
          fT3pzNpAmQ90INKjDuhlGgQ1CS2p1UgI1xe6nlsjyPnkTCUwUEupni2vYQ==
          -----END PUBLIC KEY-----
        hashAlgorithm: sha256
---
apiVersion: policy.sigstore.dev/v1beta1
kind: ClusterImagePolicy
metadata:
  name: trust-csp-cli-images
spec:
  images:
    - glob: "public.ecr.aws/aws-cli/**"
    - glob: "mcr.microsoft.com/azure-cli**"
  authorities:
    - static:
        action: pass
