apiVersion: v1
kind: Service
metadata:
  name: web-green
  namespace: dm
  labels:
    app: web-green
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.2.110
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: web-green
