apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dm
  labels:
    app: web
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.2.100
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: web
