apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: dm
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{IMAGE_NAME}"
          ports:
            - containerPort: 8888
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
