apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: dm
  labels:
    app: api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.2.200
  ports:
    - port: 8080
      targetPort: 8888
  selector:
    app: api
